<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Transact.Core.Transactions</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Transact.Infrastructure\Transact.Infrastructure.csproj" />
      <ProjectReference Include="..\Transact.Contracts\Transact.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.23" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.23" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.23">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.23" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
        <HintPath>..\..\..\..\Users\krajs\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\10.0.1\lib\net8.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
