<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Transact.Core.Users</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Transact.Contracts\Transact.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.23" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.23" />
    </ItemGroup>

</Project>
